import {
  SiPython,
  SiOpenjdk,
  SiCplusplus,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiHtml5,
  SiCss,
  SiTailwindcss,
  SiBootstrap,
  SiNodedotjs,
  SiExpress,
  SiFastapi,
  SiSpring,
  SiMysql,
  SiPostgresql,
  SiSupabase,
  SiFirebase,
  SiMongodb,
  SiPandas,
  SiNumpy,
  SiScikitlearn,
  SiTensorflow,
  SiPytorch,
  SiGit,
  SiGithub,
  SiDocker,
  SiPostman,
  SiVercel,
  SiLinux,
} from 'react-icons/si'
import { Database, Webhook } from 'lucide-react'

export const TECH_ROWS = [
  {
    category: 'Languages',
    direction: 'left',
    skills: [
      { name: 'Python', Icon: SiPython, color: '#3776AB' },
      { name: 'Java', Icon: SiOpenjdk, color: '#E76F00' },
      { name: 'C++', Icon: SiCplusplus, color: '#00599C' },
      { name: 'JavaScript', Icon: SiJavascript, color: '#F7DF1E' },
      { name: 'TypeScript', Icon: SiTypescript, color: '#3178C6' },
      { name: 'SQL', Icon: Database, color: '#D7E2EA' },
    ],
  },
  {
    category: 'Frontend',
    direction: 'right',
    skills: [
      { name: 'React', Icon: SiReact, color: '#61DAFB' },
      { name: 'Next.js', Icon: SiNextdotjs, color: '#FFFFFF' },
      { name: 'HTML5', Icon: SiHtml5, color: '#E34F26' },
      { name: 'CSS3', Icon: SiCss, color: '#1572B6' },
      { name: 'Tailwind CSS', Icon: SiTailwindcss, color: '#38BDF8' },
      { name: 'Bootstrap', Icon: SiBootstrap, color: '#7952B3' },
    ],
  },
  {
    category: 'Backend',
    direction: 'left',
    skills: [
      { name: 'Node.js', Icon: SiNodedotjs, color: '#5FA04E' },
      { name: 'Express.js', Icon: SiExpress, color: '#D7E2EA' },
      { name: 'FastAPI', Icon: SiFastapi, color: '#009688' },
      { name: 'REST API', Icon: Webhook, color: '#D7E2EA' },
      { name: 'Spring Boot', Icon: SiSpring, color: '#6DB33F' },
    ],
  },
  {
    category: 'Database & Cloud',
    direction: 'right',
    skills: [
      { name: 'MySQL', Icon: SiMysql, color: '#4479A1' },
      { name: 'PostgreSQL', Icon: SiPostgresql, color: '#4169E1' },
      { name: 'Supabase', Icon: SiSupabase, color: '#3ECF8E' },
      { name: 'Firebase', Icon: SiFirebase, color: '#FFCA28' },
      { name: 'MongoDB', Icon: SiMongodb, color: '#47A248' },
    ],
  },
  {
    category: 'AI / ML',
    direction: 'left',
    skills: [
      { name: 'Python', Icon: SiPython, color: '#3776AB' },
      { name: 'Pandas', Icon: SiPandas, color: '#D7E2EA' },
      { name: 'NumPy', Icon: SiNumpy, color: '#4DABCF' },
      { name: 'Scikit-learn', Icon: SiScikitlearn, color: '#F7931E' },
      { name: 'TensorFlow', Icon: SiTensorflow, color: '#FF6F00' },
      { name: 'PyTorch', Icon: SiPytorch, color: '#EE4C2C' },
    ],
  },
  {
    category: 'Tools',
    direction: 'right',
    skills: [
      { name: 'Git', Icon: SiGit, color: '#F05032' },
      { name: 'GitHub', Icon: SiGithub, color: '#D7E2EA' },
      { name: 'Docker', Icon: SiDocker, color: '#2496ED' },
      { name: 'Postman', Icon: SiPostman, color: '#FF6C37' },
      { name: 'Vercel', Icon: SiVercel, color: '#D7E2EA' },
      { name: 'Linux', Icon: SiLinux, color: '#FCC624' },
    ],
  },
]
